name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-release-goreleaser.yml@0.10.0
    with:
      go-version: 1.17
      version: ${{ github.event.inputs.version }}
      docker-platforms: linux/amd64,linux/arm64
      docker-tags: |
        ckotzbauer/chekr:${{ github.event.inputs.version }}
        ckotzbauer/chekr:latest
        ghcr.io/ckotzbauer/chekr:${{ github.event.inputs.version }}
        ghcr.io/ckotzbauer/chekr:latest
      cosign-repository: ghcr.io/ckotzbauer/chekr-metadata
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      pat: ${{ secrets.REPO_ACCESS }}
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
      ghcr-password: ${{ secrets.GHCR_PASSWORD }}
