name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.36.0
    with:
      install-go: true
      go-version: "1.20.3"
      install-goreleaser: true
      build-commands: make build
      build-image: true
      docker-tag: ghcr.io/ckotzbauer/chekr:latest
      scan-image: true
