name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: "v1.2.5"
          install-only: true

      - name: Build
        run: make build

      - name: Build image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ckotzbauer/chekr
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "latest"
          no_push: true
          buildargs: TARGETOS=linux,TARGETARCH=amd64

      - name: Container scan
        uses: ckotzbauer/actions-toolkit/grype@0.12.1
        with:
          scan-target: ghcr.io/ckotzbauer/chekr:latest
          fail-on: "medium"
          config-file: ".github/grype.yaml"
