name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: "0"
      - name: Build
        run: make build
