name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      - name: Build
        run: make build

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ckotzbauer/chekr:${{ github.event.inputs.version }}

      - name: Container scan
        uses: azure/container-scan@v0
        with:
          image-name: ckotzbauer/chekr
