name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: "v1.2.5"
          install-only: true

      - name: Build
        run: make build

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: |
            ghcr.io/ckotzbauer/chekr:latest

      - name: Container scan
        uses: ckotzbauer/actions-toolkit/grype@0.14.0
        with:
          scan-target: ghcr.io/ckotzbauer/chekr:latest
          fail-on: "medium"
          config-file: ".github/grype.yaml"
