name: update-k8s-deprecations

on:
  schedule:
    - cron: "0 12 * * 6"
  workflow_dispatch: {}

jobs:
  update-k8s-deprecations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - uses: actions/checkout@v3
        name: Checkout kubernetes/api
        with:
          repository: kubernetes/api
          ref: master
          path: tools/api-lifecycle-gen/api-repo

      - name: Generate
        run: make generate_k8s_deprecations

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REPO_ACCESS }}
          commit-message: "feat: Updated Kubernetes deprecations"
          branch: feature/k8s-deprecations
          delete-branch: true
          title: "Updated Kubernetes deprecations"
          labels: |
            kind/feature
